### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: hudson.util.HttpResponses.okJSON

### ISSUE THREAD

**Issue by jrichardsz** [jenkinsci/generic-webhook-trigger-plugin#22]
When I push with curl, I get this error response as html :  

```
Caused by: java.lang.NoSuchMethodError: hudson.util.HttpResponses.okJSON(Ljava/util/Map;)Lorg/kohsuke/stapler/HttpResponse;
        at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:96)
        at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
```

Windows 7
maven 3.3
java 7

Thanks in advance.

**Comment by tomasbjerre** [comment]
Jenkins version?

**Comment by jrichardsz** [comment]
Jenkins ver. 1.642.2

**Comment by tomasbjerre** [comment]
All 2.x is probably compatible. 2.7.4 or later is compatible for sure.

**Comment by jrichardsz** [comment]
I will try.
Thanks
