### ISSUE TITLE
No such property

### ISSUE THREAD

**Issue by kitingChris** [jenkinsci/generic-webhook-trigger-plugin#27]
Migrating to an AWS Jenkins I ran into the following problem:

```
node {
    properties([
        pipelineTriggers([
            [$class: 'GenericTrigger', 
                genericVariables: [
                    [expressionType: 'JSONPath', key: 'reference', value: '$.ref'],
                    [expressionType: 'JSONPath', key: 'before', value: '$.before'],
                    [expressionType: 'JSONPath', key: 'after', value: '$.after'],
                    [expressionType: 'JSONPath', key: 'repository', value: '$.repository.full_name']
                ],
                genericRequestVariables: [],
                genericHeaderVariables: []
            ]
        ])
    ])
    
    stage("run") 
        echo $reference
    }
}
```
on triggering the webhook the build fails with `No such property: $reference for class: groovy.lang.Binding`:
```
Generic Cause
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/_autobuild
[Pipeline] {
[Pipeline] properties
GenericWebhookEnvironmentContributor Received:




Contributing variables:



[Pipeline] stage
GenericWebhookEnvironmentContributor Received:




Contributing variables:



[Pipeline] { (run)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: $reference for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:282)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:286)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:27)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor517.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
Jenkins ver. 2.73.2
Generic Webhook Trigger PluginTrigger 1.20

**Comment by tomasbjerre** [comment]
Should it not be like this?

```
echo env.reference
```

And I assume you have edited the `GenericWebhookEnvironmentContributor Received:` part. There are actually contributed variables there for you?

**Comment by kitingChris** [comment]
I posted the message as it appeared. `GenericWebhookEnvironmentContributor Received` was empty.

And on the old server it worked this way...

But I tried your approach with the following error:

```
Generic Cause
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/_autobuild
[Pipeline] {
[Pipeline] properties
GenericWebhookEnvironmentContributor Received:




Contributing variables:



[Pipeline] stage
GenericWebhookEnvironmentContributor Received:




Contributing variables:



[Pipeline] { (run)
[Pipeline] echo
null
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: $reference for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:282)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:286)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:27)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor517.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by tomasbjerre** [comment]
Ok. Then I think the problem is that the plugin is triggered without any JSON in the post content.

Nothing to evaluate the JSONPath expressions in and no variables are contributed. And you get an error when trying to read a variable that does not exists.

**Comment by kitingChris** [comment]
It is a Github Webhook containing valid JSON.

**Comment by tomasbjerre** [comment]
I would try invoking it with `curl`. There is an example in the readme.

And run that curl command on the same server where Jenkins is running.

**Comment by kitingChris** [comment]
Oh Gosh! I had the `Content type` in the github webhook config still on `application/x-www-form-urlencoded`

Thanks for the help... embarassing that the problem sits 90cm in front of the monitor this time -.-

**Comment by tomasbjerre** [comment]
no problem =) I will try to make the plugin fail with a pretty message if this happens.

**Comment by KishoreMandyam** [comment]
Im getting the same error and I have the github webhook content-type set to "application/json" and it prints my variables too when I check the "Print contributed variables" checkbox, but my  jenkins job code  errors, the same thing works on my other jenkins, what am I doing wrong?


Running on Jenkins in /var/lib/jenkins/workspace/abc2.0 QA Build CICD Job
[Pipeline] {
Contributing variables:

    GIT_ACTION = synchronize
    LOGIN = abc
    NUMBER = 29
    PULL_REQUEST_TITLE = Added files for the QA environment
    PULL_REQUEST_TO_BRANCHNAME = develop
    PULL_REQUEST_URL = https://github.com/.../29
    REF = abc-patch-2
    REPO = abc-deploy
    x_github_event = pull_request
    x_github_event_0 = pull_request


[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: $REPO for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:347)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor681.invoke(Unknown Source)

**Comment by tomasbjerre** [comment]
Perhaps you are doing `$REPO` instead of `REPO` or `"$REPO"`.

What does your pipeline look like?

**Comment by KishoreMandyam** [comment]
This is my first line in my pipeline, it fails even before it starts anything, though right above it prints the values correctly, both in the Cause and in the Contributing variables, so values are coming in but 

node {
   
    def customWorkspace = '/var/lib/jenkins/workspace/' + $REPO + '_' + env.REF
....

I have tried env.REPO and $REPO both fail, I changed to other variables like REF, that failed too.
the same pipeline code works in my other jenkins install in dev env, this is qa.

**Comment by tomasbjerre** [comment]
Change it to:
`def customWorkspace = "/var/lib/jenkins/workspace/$REPO_ $REF"`
or
`def customWorkspace = '/var/lib/jenkins/workspace/' + REPO + '_' + REF`

**Comment by KishoreMandyam** [comment]
no same thing both fail
groovy.lang.MissingPropertyException: No such property: REPO_ for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at 
for 1 above

But I noticed 1 thing, the other jenkins has version 1.36 of your plugin, the new one has 1.41 where it doesnt work

**how do I get version 1.36 please?**

**Comment by tomasbjerre** [comment]
This cannot give you that error:
def customWorkspace = '/var/lib/jenkins/workspace/' + REPO + '_' + REF

**Comment by KishoreMandyam** [comment]
its the first option
def customWorkspace = "/var/lib/jenkins/workspace/$REPO_ $REF"
gives error

groovy.lang.MissingPropertyException: No such property: REPO_ for class: groovy.lang.Binding
at groovy.lang.Binding.getVariable(Binding.java:63)
at

2nd  options gives error
def customWorkspace = '/var/lib/jenkins/workspace/' + REPO + '_' + REF
gives error

No such field found: field java.lang.String REF. Administrators can decide whether to approve or reject this signature.
[Pipeline] End of Pipeline
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: No such field found: field java.lang.String REF
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.unclassifiedField(SandboxInterceptor.java:397)
	at

**Comment by KishoreMandyam** [comment]
how do I get version 1.36 please? while you debug this more?

**Comment by tomasbjerre** [comment]
https://updates.jenkins.io/download/plugins/generic-webhook-trigger/

**Comment by KishoreMandyam** [comment]
i very much appreciate you being around, responding and helping me, ill tell you if 1.36 fixed my issue in a few, I rarely get this type of Prompt support, please keep it up!

**Comment by KishoreMandyam** [comment]
node {
    def teamsUrl = 'https://outlook.office.com/webhook/09e36ed9-bd97-4a90-93d0-db91c2b2 34565c@514c0d65-3c31-4202-8182-dba994ecdb3e/JenkinsCI/a50f8c1d2cd74961965e0a87081c3bb9/aa509b4e-4364-4213-a87a-373afc32d508'
      def customWorkspace = '/var/lib/jenkins/workspace/' + $REPO + '_' + env.REF
    
    //def allDone = false
    try {
        
        message = "Started work on Pull request: $PULL_REQUEST_URL Author: $LOGIN Title: $PULL_REQUEST_TITLE Repo: $REPO"
        printstatusmessage(message)
        CurrentStep ="Inspecting PR"
        printstatusmessage("Current Step is : $CurrentStep")
        printstatusmessage("Found PR is from Branch : $REF to Branch : $PULL_REQUEST_TO_BRANCHNAME")
        ws(customWorkspace)
        {
            timeout (30)
            {
                if (env.PULL_REQUEST_TO_BRANCHNAME == PRBranch)
                {
                    //the build to QA-APP will run for a pull request open, update, but wont merge the PR
                   if (env.x_github_event == 'pull_request' && (env.GIT_ACTION == 'opened' || env.GIT_ACTION == 'synchronize'))
                    {
                      
                        stage('Build') {
                            if (env.GIT_ACTION == 'opened') {
                                 message = "Found this is a NEW Pull Request, processing build, deploy and test"
                                 printstatusmessage(message)
                                //buildEnvironment()
                            } else {
                                message = "Found this is a UPDATED Pull Request (i.e new change/commit on existing PR), processing build, deploy and test"
                                printstatusmessage(message)
                                 
                                //updateEnvironment()
                            }
                        }
                        
                        //Now deploy the code to $env
                        CurrentStep = "Now starting deploy to $env"
                        printstatusmessage("Current Step is : $CurrentStep")
                        deploytoEnv2()
                        
                        message = "ALL STEPS COMPLETED SUCCESSFULLY, DEPLOYMENT to $env 2 DONE"
                        printstatusmessage(message)
                        notifyReadyForReview2(teamsUrl)
                       
                        stage('Test') {
                            //nothing to do now but can add some testing later, if built
                            //runTests()
                        }
                        
                    } 
                   //the build to QA-APP will merge the PR, and then run run for a pull request approve
                    else if (env.x_github_event == 'pull_request_review' && env.REVIEW_STATE == 'approved') {
                    
                        stage("Merge") {
                            
                            message = "Found this is a APPROVE Pull Request, processing build and deploy to $env"
                            printstatusmessage(message)
                            
                            mergeBranch()
                            if (env.REF == 'develop' || env.REF == 'staging-deploy' || env.REF == 'qa-deploy')
                            {
                                
                            }
                            else
                            {
                                deleteBranch()
                            }
                            notifyBranchMerged(teamsUrl)
                            
                            
                           // allDone = true
                            //Now deploy the code to $env
                            CurrentStep = "Now starting deploy to $env"
                            printstatusmessage("Current Step is : $CurrentStep")
                            deploytoEnv2()
                            
                            message = "ALL STEPS COMPLETED SUCCESSFULLY, DEPLOYMENT to $env 2 DONE"
                            printstatusmessage(message)
                            notifyReadyForReview2(teamsUrl)
                        }
                    }
                    else
                    {
                        message = "THIS IS NOT A PR CREATE, UPDATE OR APPROVE ACTION, DOING NOTHING"
                        printstatusmessage(message)
                    }
                    
                   
                }
                else
                {
                    message = "PR is not to Branch " + PRBranch  +  ", so ignoring, doing nothing"
                    //message2 = "Please create a PR from your branch to " + PRBranch + " to run auto deployment to staging and automated tests"
                    message3 = "Please have another developer approve your PR (that is from your branch to " + PRBranch + " ) to auto deploy it to qa2"
                    printstatusmessage(message)
                    //printstatusmessage(message2)
                    printstatusmessage(message3)
                    
                }
            }
        }
        
    }
     catch(err) {
            message = "UNRECOVERABLE ERROR occured during processing"
            printstatusmessage(message)
            printstatusmessage("Current Step where error occured is : $CurrentStep")
            printstatusmessage("PLEASE INVESTIGATE CAUSE OF THE UNRECOVERBALE ERROR!!")
            notifyBuildFailed(teamsUrl)
            def returncode = sh 'echo $?'
            printstatusmessage("The exit code from last step processed is : '$returncode'")
            //return failed so jenkins displayed failed
            throw err
        } 
    
}

**Comment by tomasbjerre** [comment]
Well the dollar sign in `def customWorkspace = '/var/lib/jenkins/workspace/' + $REPO + '_' + env.REF` is definitely wrong.

The `org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException` should result in a script approval being available in the global Jenkins admin page. But that is strange to me, I thought it would just resolve to the environment variable.

Did you try `def customWorkspace = '/var/lib/jenkins/workspace/' + env.REPO + '_' + env.REF` ?

**Comment by KishoreMandyam** [comment]
env.REPO was what I had originally, they all fail env.REPO, $REPO, REPO, this is a new jenkins install, so am I missing some other plugins, your plugin depends on or something?

**Comment by KishoreMandyam** [comment]
yes

**Comment by KishoreMandyam** [comment]
I did a diff of the config and code of where same stuff works to where it doesn't, and don't see anything different, so im just perplexed and stuck, but I have another guy on my team who setup the other one, im asking him to look in a few hours, lets see what he finds.

I even copied over the same config and created a new job, and then copied in the code , but still same issue.

**Comment by tomasbjerre** [comment]
I made a test with plugin version 1.41 and Jenkins 2.121.1.

I have this config:
![env1](https://user-images.githubusercontent.com/439571/44215450-da8fc900-a172-11e8-9629-9f81cc599826.png)

I have this pipeline code:
```
node {
    def teamsUrl = 'https://outlook.office.com/webhook/09e36ed9-bd97-4a90-93d0-db91c2b2 34565c@514c0d65-3c31-4202-8182-dba994ecdb3e/JenkinsCI/a50f8c1d2cd74961965e0a87081c3bb9/aa509b4e-4364-4213-a87a-373afc32d508'
    def customWorkspace = '/var/lib/jenkins/workspace/' + env.REPO + '_' + env.REF
    def customWorkspace2 = '/var/lib/jenkins/workspace/' + REPO + '_' + REF
    def customWorkspace3 = "/var/lib/jenkins/workspace/$REPO" + '_' + "$REF"

    println teamsUrl
    println customWorkspace
    println customWorkspace2
    println customWorkspace3
}
```

I invoke it with:
```
curl -v -H "Content-Type: application/json" -X POST -d '{ "REPO": "abc-deploy", "REF": "abc-patch-2" }' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=pipe
```

And I get this in the job log:

```
Generic Cause
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on Jenkins in /home/bjerre/workspace/generic-webhook-trigger-plugin/work/workspace/pipe
[Pipeline] {
GenericWebhookEnvironmentContributor
 Received:

{ "REPO": "abc-deploy", "REF": "abc-patch-2" }


Contributing variables:

    REF = abc-patch-2
    REPO = abc-deploy


[Pipeline] echo
https://outlook.office.com/webhook/09e36ed9-bd97-4a90-93d0-db91c2b2 34565c@514c0d65-3c31-4202-8182-dba994ecdb3e/JenkinsCI/a50f8c1d2cd74961965e0a87081c3bb9/aa509b4e-4364-4213-a87a-373afc32d508
[Pipeline] echo
/var/lib/jenkins/workspace/abc-deploy_abc-patch-2
[Pipeline] echo
/var/lib/jenkins/workspace/abc-deploy_abc-patch-2
[Pipeline] echo
/var/lib/jenkins/workspace/abc-deploy_abc-patch-2
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by KishoreMandyam** [comment]
ok i took out my whole code and just added echo statements like you did and it works!!

so must be something wrong in my code somewhere that it doesn't like, i have to introduce my code but by bit and see what it doesn't like in it!!

Whew! thanks for all your help

**Comment by KishoreMandyam** [comment]
its very silly!!  but the cause of my issue and error was I had a environment variable named 'env' in my code at the start!! This is a reserved word as its used in env.variable, once I fixed that problem was solved.

better error would help, not sure its in groovy or in your plugin!

**Comment by tomasbjerre** [comment]
Ok!
