### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property

### ISSUE THREAD

**Issue by Noamrok** [jenkinsci/generic-webhook-trigger-plugin#286]
Hi

Since upgrading our jaas to this new version we are having issues with the plugin. The plugin failed to read a variable configured in it. In our case we have a var name tagName which is being populated with a value from github webhook.

 * Plugin version used: 1.88.1
 * Jenkins version used: 2.414.3
 * Your configuration:
   * We have a variable name: tagName which sets from the github webhook $.release.tag_name
   * We do something simple:
```
   pipeline {
    agent any

    stages {
        stage('Update new version in landscape') {
            when {
                expression { 
                    return  tagName 
                }
            }
           steps { ... }
```
 * Build job log:
 ```
17:53:49  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 5641326f-0ab6-4f23-aa67-92accbc6b4c6
17:53:49  hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: tagName for class: WorkflowScript
17:53:49  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
17:53:49  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:471)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:377)
17:53:49  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
17:53:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:347)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:375)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:379)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:355)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:355)
17:53:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:355)
17:53:49  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.getProperty(LoggingInvoker.java:121)
17:53:49  	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
17:53:49  	at WorkflowScript.run(WorkflowScript:14)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.when.impl.ExpressionConditionalScript.evaluate(ExpressionConditionalScript.groovy:48)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter$WhenEvaluator.evaluateWhen(ModelInterpreter.groovy:856)
17:53:49  	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.every(CpsDefaultGroovyMethods:2323)
17:53:49  	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.every(CpsDefaultGroovyMethods:2344)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter$WhenEvaluator.evaluateWhen(ModelInterpreter.groovy:855)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter$WhenEvaluator.evaluateWhen(ModelInterpreter.groovy)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter$WhenEvaluator.passedOrNotEvaluated(ModelInterpreter.groovy:846)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:273)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:586)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:585)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:272)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:356)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:355)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:261)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:618)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:617)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:259)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:443)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:442)
17:53:49  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:254)
17:53:49  	at ___cps.transform___(Native Method)
17:53:49  	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:73)
17:53:49  	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
17:53:49  	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:65)
17:53:49  	at jdk.internal.reflect.GeneratedMethodAccessor393.invoke(Unknown Source)
17:53:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:53:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
17:53:49  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
17:53:49  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
17:53:49  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
17:53:49  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
17:53:49  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
17:53:49  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
17:53:49  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
17:53:49  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
17:53:49  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:97)
17:53:49  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17:53:49  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
17:53:49  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
17:53:49  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
17:53:49  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
17:53:49  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
17:53:49  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17:53:49  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
17:53:49  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
17:53:49  	at java.base/java.lang.Thread.run(Thread.java:833)
17:53:49  Finished: FAILURE
```
https://ugdev.jaas-gcp.cloud.sap.corp/job/update-landscapes-with-product-version/488/console

**Comment by tomasbjerre** [comment]
Try 1.88.2 https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/285
