### ISSUE TITLE
Add defaultValue attribute to GenericVariables

### ISSUE THREAD

**Issue by andrehcampos** [jenkinsci/generic-webhook-trigger-plugin#35]
Hi, thanks for your work with the plugin, it is great!

I'd like to suggest adding the **defaultValue** attribute to GenericVariables, as the example below:

`genericVariables: [
   [expressionType: 'JSONPath', key: 'VAR', value: '$.node', defaultValue: 'some_value']`

**Comment by tomasbjerre** [comment]
Releasing this in 1.25 now.

**Comment by andrehcampos** [comment]
Thank you @tomasbjerre

**Comment by opack** [comment]
Hello !

Unfortunately, this does not seem to work with empty string :-( I just wanted to have the variables created with an empty value if not possible to correctly initialize them, but when the JSONPath cannot be resolved, the variable is not created, leading to missing variable errors.

Thus, it seems that the default value for defaultValue (huhu), which is an empty string, is not applied.

Do you confirm?

Thanks ! :-)

**Comment by tomasbjerre** [comment]
Perhaps. But that is not a major issue right? Just check for its existens before reading it?

**Comment by opack** [comment]
Yes I could do that, but in a declarative pipeline it can be quite heavy to always check that, whereas an empty string could perfectly fit for a use in a echoed message or a variable passed to a shell script (for example).

Another example is a pipeline triggered either after a push or on a merge request. I have variables populate for a JSON sent on a push, and other variables for a JSON sent on a merge request. Unfortunately, some common information are not placed in the same JSONPath. For example: the branch can be:
* `[key: 'MR_FROM_BRANCH', value: '$.object_attributes.source_branch']`
* `[key: 'PUSH_REF', value: '$.ref']` 
Based on this, I want:
* To feed the `causeString` with something like `causeString: "Triggered on $MR_FROM_BRANCH$PUSH_REF"
* To create a `environment` variables as `REF = "$MR_FROM_BRANCH$PUSH_REF"
* To be able to check for $PUSH_REF emptiness
...
Currently, I have to rely on a Groovy function to initialize my "common" variables:
```
environment {
        PROJECT_ID = getValue(env.PUSH_PROJECT_ID, env.MR_PROJECT_ID)
        LAST_COMMIT = getValue(env.PUSH_LAST_COMMIT, env.MR_LAST_COMMIT)
        REF = getValue(env.PUSH_REF, env.MR_FROM_BRANCH)
}
```
Later I need to create this function:
```
def getValue(preferedValue, defaultValue) {
    if (preferedValue == 'none') {
        return defaultValue;
    }
    return preferedValue;
}
```
This is not ideal, and does not help me with the `causeString` :-(

I also tried some evolved JSONPath to use either one value of the other, like `[key: 'PROJECT_ID', value: '$.[object_attributes.target_project_id,project.id]']` but it does not work :-(

**Comment by opack** [comment]
I thought of another way to have what I want. In fact, what I want is to have two different triggers: one for push, one for merge requests. Both of them will populate some variables with an identical name. Thus, the rest of my pipeline does not have to care about which event caused it to be triggered :-)

Problem is that if I duplicate the GenericTrigger in the triggers block, I end up with the following error:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 6: Duplicate trigger name: "GenericTrigger" @ line 6, column 5.
       triggers {
       ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.lambda$doParse$0(CpsGroovyShell.java:135)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:132)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```
Do you know a way to include multiple times the same trigger class, configured differently? Thanks in advance ;-)

**Comment by tomasbjerre** [comment]
Releasing 1.53 now with support for empty default values.

You cannot add the same trigger twice, not something regulated by this plugin, it is like that in Jenkins.

If I were you I would probably create two jobs. Because I would most likely want to do different things. And I would have the shared code in a shared library.

**Comment by opack** [comment]
Thanks for the support for empty values and your real quick release 👍 

So sad for the double trigger :-( I was afraid of that. In my case I precisely want to do exactly all the same thing all along the pipeline. Every step is the same, except one thing: if triggered by a merge request, then in some stages I add a note to the merge request. Thus, having two jobs would duplicate almost all my pipeline :-(

**Comment by opack** [comment]
Hello again :-)

Sorry to bother you again. As I said previously, the `defaultValue` works great ! But it does not work in case of manual execution of the pipeline :-( I explain all below, but please let me know if you think that I should create a new issue ;-)

Here is the use case. I would like to be able to simply manually run the pipeline for some reason, in example if some error happened, or if I want to perform the operations in the pipeline once again (to update the targeted environment...).

However, if I run the pipeline manually it seems like the `genericVariables` are not evaluated, and thus not created with their default value.
In my case, I have a `causeString` that has this value:
```
causeString: "Triggered after $OBJECT_KIND"
```
In my `genericVariables`, I have
```
[key: 'OBJECT_KIND', value: '$.object_kind', defaultValue: 'manual action']
```

This is working fine when the pipeline is triggered either by a push or a merge request, and the cause string gets updated. But when I execute it manually I have this error:
```
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: OBJECT_KIND for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:289)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:293)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:269)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:31)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:61)
	at WorkflowScript.run(WorkflowScript:7)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
Although I expected it to not crash and update the cause string to `Triggered after manual action`.
