### ISSUE TITLE
NullPointerException at GenericTriggerResults (version 1.25)

### ISSUE THREAD

**Issue by andrehcampos** [jenkinsci/generic-webhook-trigger-plugin#37]
**Groovy code:**
`      pipelineTriggers([[
        $class: 'GenericTrigger',
          genericVariables: [
            // Bitbucket EventPayloads: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push
            [key: 'EVENT_REPOSITORY_NAME', value: '$.repository.full_name',     expressionType: 'JSONPath'],
            [key: 'EVENT_PUSH_TYPE',       value: '$.push.changes[0].new.type', expressionType: 'JSONPath'],
            [key: 'BRANCH_OR_TAG',         value: '$.push.changes[0].new.name', expressionType: 'JSONPath'],
          ],
          genericRequestVariables: [
            [key: 'WAR_PROFILE', regexpFilter: ''],
            [key: 'EXEC_DEPLOY', regexpFilter: ''],
            [key: 'UPDATEBUILD', regexpFilter: ''],
          ],
          regexpFilterText: '$EVENT_PUSH_TYPE',
          regexpFilterExpression: 'tag'
        ]`

**Response Body:**
`{
  "status": "ok",
  "data": {
    "triggerResults": {
      "pipeline-webhook-test": "Exception occurred, full stack trace in Jenkins server log. Thrown in: org.jenkinsci.plugins.gwt.GenericTriggerResults:21",
    }
  }
}`

**Jenkins Log:** 
`java.lang.NullPointerException
	at org.jenkinsci.plugins.gwt.GenericTriggerResults.<init>(GenericTriggerResults.java:21)
	at org.jenkinsci.plugins.gwt.GenericTrigger.trigger(GenericTrigger.java:118)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:87)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:56)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.process(GenericWebHookRequestReceiver.java:125)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:58)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at 
`

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericTriggerResults.java#L21

Will fix it later today!

**Comment by tomasbjerre** [comment]
Releasing fix in 1.26 now.

**Comment by andrehcampos** [comment]
Thank you Tomas.

2018-02-07 13:23 GMT-02:00 Tomas Bjerre <notifications@github.com>:
