### ISSUE TITLE
NullPointerException when trying to trigger job

### ISSUE THREAD

**Issue by spudfkc** [jenkinsci/generic-webhook-trigger-plugin#62]
* Plugin version used.
1.39
 * Your configuration.
My Jenkinsfile
```groovy
#!groovy
properties([
  parameters([
    string(name: 'APP_ID', defaultValue: ''),
    choice(name: 'APP_ENV', defaultValue: 'testing'),
    string(name: 'DATABASES_BRANCH', defaultValue: 'master'),
    string(name: 'DATABASES', defaultValue: ''),
    booleanParam(name: 'DROP_DATABASES', defaultValue: new Boolean(true)),
    booleanParam(name: 'AUTO_DISCOVER_DATABASES', defaultValue: new Boolean(false)),
    booleanParam(name: 'DEBUG', defaultValue: new Boolean(false)),
  ]),
  pipelineTriggers([
    [$class: 'GenericTrigger',
     genericVariables: [
      [expressionType: 'JSONPath', key: 'APP_ID', value: '$.app_id', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'APP_ENV', value: '$.app_env', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'DATABASES', value: '$.databases', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'AUTO_DISCOVER_DATABASES', value: '$.auto_discover_databases', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'DEBUG', value: '$.debug', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'DROP_DATABASES', value: '$.drop_databases', defaultValue: ''],
      [expressionType: 'JSONPath', key: 'DATABASES_BRANCH', value: '$.databases_branch', defaultValue: ''],
     ],
     regexpFilterText: '',
     regexpFilterExpression: ''
    ]
  ])
])

node {
  stage('test') {
    sh('echo hello')
  }
}
```

 * A `curl` command and its response.
```bash
curl -v -XPOST --url "https://JENKINS/generic-webhook-trigger/invoke" -d '{"app_id": "5", "app_env": "testing", "databases": [], "auto_discover_databases": false, "drop_databases": false, "debug": true, "databases_branch": "master"}' --header "Content-type:application/json"
```

curl response
```json
{"status":"ok","data":{"triggerResults":{"mytestjob/remote-trigger-job":"Exception occurred, full stack trace in Jenkins server log. Thrown in: org.jenkinsci.plugins.gwt.ParameterActionUtil:73"}}}
```

 * Expected result and actual result.
Full Stacktrace
```
2018-07-09 18:36:45.293 SEVERE  [org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver] (org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver doInvoke) mytestjob/remote-trigger-job
java.lang.NullPointerException
	at org.jenkinsci.plugins.gwt.ParameterActionUtil.getStringValue(ParameterActionUtil.java:73)
	at org.jenkinsci.plugins.gwt.ParameterActionUtil.getParameterValue(ParameterActionUtil.java:54)
	at org.jenkinsci.plugins.gwt.ParameterActionUtil.getParametersWithRespectToDefaultValues(ParameterActionUtil.java:40)
	at org.jenkinsci.plugins.gwt.ParameterActionUtil.createParameterAction(ParameterActionUtil.java:24)
	at org.jenkinsci.plugins.gwt.GenericTrigger.trigger(GenericTrigger.java:121)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:109)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:58)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:52)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.process(GenericWebHookRequestReceiver.java:147)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am experience some unexpected behavior with this webhook plugin - a [NullPointerException when trying to do stuff with a default value](https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/ParameterActionUtil.java#L73)?

Is there something wrong with my configuration, or is this a bug? It looks to me like I have things configured correctly - I'm not trying to do anything complex.

**Comment by tomasbjerre** [comment]
What version of Jenkins?

**Comment by tomasbjerre** [comment]
This looks strange:
```
choice(name: 'APP_ENV', defaultValue: 'testing'),
```
I don't see any `defaultValue` on the choice parameter. I would expect this:
```
choice(name: 'APP_ENV', choices: ['testing']),
```

**Comment by tomasbjerre** [comment]
Releasing 1.40 now with a fix.
