### ISSUE TITLE
Im getting same error as in https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/27

### ISSUE THREAD

**Issue by KishoreMandyam** [jenkinsci/generic-webhook-trigger-plugin#68]
When reporting a bug, please try to provide as much information as possible.

 * Plugin version used. : 1.41
 * Your configuration.
  * Variables configured, names, expressions...
 * Post content received. It can be found in the job execution log. People using GitHub often forget to set the content type in "Manage webhook" when configuring the webhook at GitHub.
 * A `curl` command and its response.
 * Expected result and actual result.

You may also have a look at the test cases as they should answer the most common questions:
 
  https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

If you are fiddling with expressions, you may want to checkout:

* [This JSONPath site](https://jsonpath.curiousconcept.com/)
* [This XPath site](http://www.freeformatter.com/xpath-tester.html)
* [This regexp site](https://jex.im/regulex/)

A Curl command can look something like this:
```
curl -v -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken
```

I am getting same error as in issue #27 , 

Im getting the same error and I have the github webhook content-type set to "application/json" and it prints my variables too when I check the "Print contributed variables" checkbox, but my jenkins job code errors, the same thing works on my other jenkins, what am I doing wrong?

Running on Jenkins in /var/lib/jenkins/workspace/abc2.0 QA Build CICD Job
[Pipeline] {
Contributing variables:

GIT_ACTION = synchronize
LOGIN = abc
NUMBER = 29
PULL_REQUEST_TITLE = Added files for the QA environment
PULL_REQUEST_TO_BRANCHNAME = develop
PULL_REQUEST_URL = https://github.com/.../29
REF = abc-patch-2
REPO = abc-deploy
x_github_event = pull_request
x_github_event_0 = pull_request
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: $REPO for class: groovy.lang.Binding
at groovy.lang.Binding.getVariable(Binding.java:63)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
at WorkflowScript.run(WorkflowScript:347)
at cps.transform(Native Method)
at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
at sun.reflect.GeneratedMethodAccessor681.invoke(Unknown Source)

**Comment by KishoreMandyam** [comment]
running via curl gave me same error

**Comment by KishoreMandyam** [comment]
i receive a 200 for webhook delivery and my variable is configured like this for example

Post contant parameters
Variable : REF
Expression : $.pull_request.head.ref

**Comment by tomasbjerre** [comment]
Perhaps you are doing `$REPO` instead of `REPO` or `"$REPO"`.

What does your pipeline look like?

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/27
