### ISSUE TITLE
Hooks doesn't work when declarative pipeline is retrieved from a shared library

### ISSUE THREAD

**Issue by yasassri** [jenkinsci/generic-webhook-trigger-plugin#95]
I tried to use the pipeline which gets triggered through a shared library[[1](https://jenkins.io/doc/book/pipeline/shared-libraries/)]. But it didn't work properly, Following is the simple library code, and it seems the variables didn't injected to the environment. Also sometimes trigger didn't kick off the build.

```
def call() {
    // Setting the current pipeline context, this should be done initially
    //PipelineContext.instance.setContext(this)
 
    pipeline {
        agent any
        triggers {
            GenericTrigger(
                    genericVariables: [
                            [expressionType: 'JSONPath', key: 'sshUrl', value: '$.ssh_url'],
                            [expressionType: 'JSONPath', key: 'repoName', value: '$.repository.name'],
                            [expressionType: 'JSONPath', key: 'branch', value: '$.ref', regexpFilter: 'refs/heads/']
                    ],
                    regexpFilterText: '',
                    regexpFilterExpression: ''
            )
        }
        tools {
            jdk 'jdk8'
        }

        stages {
            stage('Receive web Hooks') {
                steps {
                    script {
                        // Cloning the git repository
                        echo "The git branch is : ${branch}"
                        echo "The git branch is : ${repoName}"
                        echo "The git branch is : ${sshUrl}"
                        // log.info("The git repo name is : ${repoName}")
                    }
                }
            }
        }
    }
}
```

Error I got,

```
groovy.lang.MissingPropertyException: No such property: branch for class: WebHookAnalyzer
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WebHookAnalyzer.call(/testgrid/jenkins-home/jobs/git-web-hook/builds/77/libs/yasassri/vars/WebHookAnalyzer.groovy:57)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tomasbjerre** [comment]
How do you trigger the build?

**Comment by yasassri** [comment]
> How do you trigger the build?

The job is triggered through a github web-hook.

**Comment by tomasbjerre** [comment]
Which checkbox do you tick?
What is the response of the webhook call when it does not work?

**Comment by tomasbjerre** [comment]
What was the json being sent?

**Comment by yasassri** [comment]
```
{
  "ref": "refs/heads/testbranch",
  "before": "0000000000000000000000000000000000000000",
  "after": "588ea9a7097c984a770f7bdcfcc9c9f24fd28463",
  "created": true,
  "deleted": false,
  "forced": false,
  "base_ref": "refs/heads/master",
  "compare": "https://github.com/yasassri/web-hook-test/compare/testbranch",
  "commits": [

  ],
  "head_commit": {
    "id": "588ea9a7097c984a770f7bdcfcc9c9f24fd28463",
    "tree_id": "ab7397918258f2c83d5a4d07d6afb174fc4b9359",
    "distinct": true,
    "message": "Update README.md",
    "timestamp": "2018-12-02T22:23:16+05:30",
    "url": "https://github.com/yasassri/web-hook-test/commit/588ea9a7097c984a770f7bdcfcc9c9f24fd28463",
    "author": {
      "name": "Yasassri Ratnayake",
      "email": "ycrnet@gmail.com",
      "username": "yasassri"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "README.md"
    ]
  },
  "repository": {
    "id": 159813328,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTk4MTMzMjg=",
    "name": "web-hook-test",
    "full_name": "yasassri/web-hook-test",
    "private": false,
    "owner": {
      "name": "yasassri",
      "email": "ycrnet@gmail.com",
      "login": "yasassri",
      "id": 7681361,
      "node_id": "MDQ6VXNlcjc2ODEzNjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7681361?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/yasassri",
      "html_url": "https://github.com/yasassri",
      "followers_url": "https://api.github.com/users/yasassri/followers",
      "following_url": "https://api.github.com/users/yasassri/following{/other_user}",
      "gists_url": "https://api.github.com/users/yasassri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/yasassri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/yasassri/subscriptions",
      "organizations_url": "https://api.github.com/users/yasassri/orgs",
      "repos_url": "https://api.github.com/users/yasassri/repos",
      "events_url": "https://api.github.com/users/yasassri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/yasassri/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/yasassri/web-hook-test",
    "description": "This repo is used to test webhooks",
    "fork": false,
    "url": "https://github.com/yasassri/web-hook-test",
    "forks_url": "https://api.github.com/repos/yasassri/web-hook-test/forks",
    "keys_url": "https://api.github.com/repos/yasassri/web-hook-test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/yasassri/web-hook-test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/yasassri/web-hook-test/teams",
    "hooks_url": "https://api.github.com/repos/yasassri/web-hook-test/hooks",
    "issue_events_url": "https://api.github.com/repos/yasassri/web-hook-test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/yasassri/web-hook-test/events",
    "assignees_url": "https://api.github.com/repos/yasassri/web-hook-test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/yasassri/web-hook-test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/yasassri/web-hook-test/tags",
    "blobs_url": "https://api.github.com/repos/yasassri/web-hook-test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/yasassri/web-hook-test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/yasassri/web-hook-test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/yasassri/web-hook-test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/yasassri/web-hook-test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/yasassri/web-hook-test/languages",
    "stargazers_url": "https://api.github.com/repos/yasassri/web-hook-test/stargazers",
    "contributors_url": "https://api.github.com/repos/yasassri/web-hook-test/contributors",
    "subscribers_url": "https://api.github.com/repos/yasassri/web-hook-test/subscribers",
    "subscription_url": "https://api.github.com/repos/yasassri/web-hook-test/subscription",
    "commits_url": "https://api.github.com/repos/yasassri/web-hook-test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/yasassri/web-hook-test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/yasassri/web-hook-test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/yasassri/web-hook-test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/yasassri/web-hook-test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/yasassri/web-hook-test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/yasassri/web-hook-test/merges",
    "archive_url": "https://api.github.com/repos/yasassri/web-hook-test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/yasassri/web-hook-test/downloads",
    "issues_url": "https://api.github.com/repos/yasassri/web-hook-test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/yasassri/web-hook-test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/yasassri/web-hook-test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/yasassri/web-hook-test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/yasassri/web-hook-test/labels{/name}",
    "releases_url": "https://api.github.com/repos/yasassri/web-hook-test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/yasassri/web-hook-test/deployments",
    "created_at": 1543576951,
    "updated_at": "2018-12-02T16:53:18Z",
    "pushed_at": 1543770647,
    "git_url": "git://github.com/yasassri/web-hook-test.git",
    "ssh_url": "git@github.com:yasassri/web-hook-test.git",
    "clone_url": "https://github.com/yasassri/web-hook-test.git",
    "svn_url": "https://github.com/yasassri/web-hook-test",
    "homepage": null,
    "size": 50,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "yasassri",
    "email": "ycrnet@gmail.com"
  },
  "sender": {
    "login": "yasassri",
    "id": 7681361,
    "node_id": "MDQ6VXNlcjc2ODEzNjE=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/7681361?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yasassri",
    "html_url": "https://github.com/yasassri",
    "followers_url": "https://api.github.com/users/yasassri/followers",
    "following_url": "https://api.github.com/users/yasassri/following{/other_user}",
    "gists_url": "https://api.github.com/users/yasassri/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yasassri/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yasassri/subscriptions",
    "organizations_url": "https://api.github.com/users/yasassri/orgs",
    "repos_url": "https://api.github.com/users/yasassri/repos",
    "events_url": "https://api.github.com/users/yasassri/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yasassri/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by yasassri** [comment]
@tomasbjerre the json path for the ssh_url is not correct in the code I shared, I actually fixed that as well. Have you ever tried the plugin with a shared library?

**Comment by tomasbjerre** [comment]
Yes, l have tried it with shared library. But not for a while.

You should be able to view the configured job in Jenkins GUI after it has run once. The pipeline needs to run at least once to configure itself. And after that it can run from being triggered by the hook. This is all just how pipelines work and nothing to do with the plugin.

This is why I prefer to use Job DSL to create pipeline jobs with the plugin configured in Job DSL.

So the question is really what do you see being configured after first manual trigger of the job?

**Comment by Hermain** [comment]
FYI, I got it working in scripted pipeline. The only "issue" is that changes to the parameters only take effect after executing the pipeline once:

```def call(body) {

    //this is the configuration of the generic webhook plugin
    properties([
            pipelineTriggers([
                    [$class: 'GenericTrigger',
                     token: 'mrs-publish-dev',
                     genericVariables: [
                             [
                                     key: 'accessToken',
                                     value: '$.AccessToken',
                                     expressionType: 'JSONPath', //Optional, defaults to JSONPath
                                     regexpFilter: '', //Optional, defaults to empty string
                                     defaultValue: '' //Optional, defaults to empty string
                             ],
                             [
                                     key: 'mrsBackendUrl',
                                     value: '$.MrsBackendUrl',
                                     expressionType: 'JSONPath', //Optional, defaults to JSONPath
                                     regexpFilter: '', //Optional, defaults to empty string
                                     defaultValue: '' //Optional, defaults to empty string
                             ]
                     ],
                     causeString: 'Triggered by webhook',
                     printContributedVariables: true,
                     printPostContent: true,
                    ]
            ])
    ])``` hope this helps

**Comment by tomasbjerre** [comment]
Nice, hopefully it will help someone else having same problem.

**Comment by cantSleepNow** [comment]
I also got it working from library with declarative pipeline. I ran only few tests, but everything works so far
```
def call(String tokenz){ 
pipeline {
  agent{label "docker"}
   triggers {
    GenericTrigger(
        genericVariables: [
            [key: 'otherVarName', value: '$']
            ],
         causeString: 'Triggered on ',
         token: tokenz,
         printContributedVariables: true,
         printPostContent: true,
         silentResponse: false,
    )
  }
  stages {
    stage('Some step') {
      steps {
        script{
            def jsonObj = readJSON text: otherVarName
            echo "reading jso now"
            echo "${jsonObj.eventKey}"
        }
      }
    }
  }
  post{
		cleanup{
			cleanWs()
		}//cleanup
	}
}
}
```
